
export type City = {
  name: string;
  category: 'X' | 'Y' | 'Z';
};

export const cities: City[] = [
  // X Category
  { name: 'Ahmedabad', category: 'X' },
  { name: 'Bangalore/Bengaluru', category: 'X' },
  { name: 'Chennai', category: 'X' },
  { name: 'Delhi', category: 'X' },
  { name: 'Greater Mumbai', category: 'X' },
  { name: 'Hyderabad', category: 'X' },
  { name: 'Kolkata', category: 'X' },
  { name: 'Pune', category: 'X' },

  // Y Category
  { name: 'Agra', category: 'Y' },
  { name: 'Ajmer', category: 'Y' },
  { name: 'Aligarh', category: 'Y' },
  { name: 'Allahabad', category: 'Y' },
  { name: 'Amravati', category: 'Y' },
  { name: 'Amritsar', category: 'Y' },
  { name: 'Asansol', category: 'Y' },
  { name: 'Aurangabad', category: 'Y' },
  { name: 'Bareilly', category: 'Y' },
  { name: 'Belgaum', category: 'Y' },
  { name: 'Bhavnagar', category: 'Y' },
  { name: 'Bhiwandi', category: 'Y' },
  { name: 'Bhopal', category: 'Y' },
  { name: 'Bhubaneswar', category: 'Y' },
  { name: 'Bikaner', category: 'Y' },
  { name: 'Bokaro Steel City', category: 'Y' },
  { name: 'Chandigarh', category: 'Y' },
  { name: 'Coimbatore', category: 'Y' },
  { name: 'Cuttack', category: 'Y' },
  { name: 'Dehradun', category: 'Y' },
  { name: 'Dhanbad', category: 'Y' },
  { name: 'Durg-Bhilai Nagar', category: 'Y' },
  { name: 'Durgapur', category: 'Y' },
  { name: 'Erode', category: 'Y' },
  { name: 'Faridabad', category: 'Y' },
  { name: 'Firozabad', category: 'Y' },
  { name: 'Ghaziabad', category: 'Y' },
  { name: 'Gorakhpur', category: 'Y' },
  { name: 'Greater Visakhapatnam', category: 'Y' },
  { name: 'Gulbarga', category: 'Y' },
  { name: 'Guntur', category: 'Y' },
  { name: 'Gurgaon', category: 'Y' },
  { name: 'Guwahati', category: 'Y' },
  { name: 'Gwalior', category: 'Y' },
  { name: 'Hubli-Dharwad', category: 'Y' },
  { name: 'Indore', category: 'Y' },
  { name: 'Jabalpur', category: 'Y' },
  { name: 'Jaipur', category: 'Y' },
  { name: 'Jalandhar', category: 'Y' },
  { name: 'Jammu', category: 'Y' },
  { name: 'Jamnagar', category: 'Y' },
  { name: 'Jamshedpur', category: 'Y' },
  { name: 'Jhansi', category: 'Y' },
  { name: 'Jodhpur', category: 'Y' },
  { name: 'Kannur', category: 'Y' },
  { name: 'Kanpur', category: 'Y' },
  { name: 'Kochi', category: 'Y' },
  { name: 'Kolhapur', category: 'Y' },
  { name: 'Kollam', category: 'Y' },
  { name: 'Kota', category: 'Y' },
  { name: 'Kozhikode', category: 'Y' },
  { name: 'Lucknow', category: 'Y' },
  { name: 'Ludhiana', category: 'Y' },
  { name: 'Madurai', category: 'Y' },
  { name: 'Malappuram', category: 'Y' },
  { name: 'Malegaon', category: 'Y' },
  { name: 'Mangalore', category: 'Y' },
  { name: 'Mathura-Vrindavan (Municipal Corporations)', category: 'Y' },
  { name: 'Meerut', category: 'Y' },
  { name: 'Mohali', category: 'Y' },
  { name: 'Moradabad', category: 'Y' },
  { name: 'Mysore', category: 'Y' },
  { name: 'Nagpur', category: 'Y' },
  { name: 'Nanded-Waghala', category: 'Y' },
  { name: 'Nashik', category: 'Y' },
  { name: 'Nellore', category: 'Y' },
  { name: 'Noida', category: 'Y' },
  { name: 'Patna', category: 'Y' },
  { name: 'Puducherry/Pondicherry', category: 'Y' },
  { name: 'Raipur', category: 'Y' },
  { name: 'Rajkot', category: 'Y' },
  { name: 'Ranchi', category: 'Y' },
  { name: 'Rourkela', category: 'Y' },
  { name: 'S.A.S. Nagar', category: 'Y' },
  { name: 'Saharanpur', category: 'Y' },
  { name: 'Salem', category: 'Y' },
  { name: 'Sangli', category: 'Y' },
  { name: 'Siliguri', category: 'Y' },
  { name: 'Solapur', category: 'Y' },
  { name: 'Srinagar', category: 'Y' },
  { name: 'Surat', category: 'Y' },
  { name: 'Thiruvananthapuram', category: 'Y' },
  { name: 'Thrissur', category: 'Y' },
  { name: 'Tiruchirappalli', category: 'Y' },
  { name: 'Tiruppur', category: 'Y' },
  { name: 'Ujjain', category: 'Y' },
  { name: 'Vadodara', category: 'Y' },
  { name: 'Varanasi', category: 'Y' },
  { name: 'Vasai-Virar City', category: 'Y' },
  { name: 'Vijayawada', category: 'Y' },
  { name: 'Warangal', category: 'Y' },

  // Z Category
  { name: 'Other Cities', category: 'Z' },
];
